### ISSUE TITLE
Scrolling capturing not possible?

### ISSUE THREAD

**Issue by jayesh83** [PatilShreyas/Capturable#40]
Shreyas, is it possible to capture entire lazyColum/colum of wrapping content (scrolling) in a bitmap instead of just capturing what is on the screen?

**Comment by PatilShreyas** [comment]
In case of LazyColumn, it's not possible to capture. Since you are aware that LazyColumn renders items when item has to actually render on the screen. But if that's only need, use `Column`.

**Comment by sac-rana** [comment]
I am having the same problem. I am using a scrollable column as you said but the bitmap still contains only the part which is currently visible.

**Comment by jayesh83** [comment]
changing to column still doesn't work, I've two Text() inside a column. It still captures only what's visible even though there's more content. Tried to make it scrollable too but no luck

**Comment by xing634325131** [comment]
I also can't find a solution to this problem, maybe could hope in the future.

**Comment by PatilShreyas** [comment]
This issue has been fixed and released in version 2.0.0.

**Comment by dessalines** [comment]
Still doesn't seem to work. At least with `.verticalScroll(`
